name = "olsp-24h-challenge"
main = "src/index.js"
compatibility_date = "2025-09-13"

routes = [
    { pattern = "jointhesprint.co/*", zone_name = "jointhesprint.co" }
]

[build]
command = "npm run build"

[assets]
directory = "./dist"