// This file is auto-generated by build.mjs. Do not edit manually.

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    let path = url.pathname;

    // --- Path rewriting logic ---
    if (path === "/") {
      path = "/index.html";
    } else if (!path.split('/').pop().includes('.')) {
      path = path + ".html";
    }
    
    const newUrl = new URL(path, request.url);
    const newRequest = new Request(newUrl, request);

    // --- Custom PDF download logic ---
    if (path === '/cheat-sheet.pdf') {
      // Fetch the asset from the store
      const asset = await env.ASSETS.fetch(newRequest);

      // Create a new response with the same body but new headers to force download
      const headers = new Headers(asset.headers);
      headers.set('Content-Disposition', 'attachment; filename="24-Hour-Commission-Cheat-Sheet.pdf"');
      
      return new Response(asset.body, {
        status: asset.status,
        statusText: asset.statusText,
        headers: headers,
      });
    }

    // For all other files, let the default asset handler serve them
    return env.ASSETS.fetch(newRequest);
  },
};