// This file is auto-generated by build.mjs. Do not edit manually.

import disclaimerHtml from './../disclaimer.html';
import indexHtml from './../index.html';
import pdfHtml from './../pdf.html';
import privacyHtml from './../privacy.html';
import termsHtml from './../terms.html';

const pages = {
  '/disclaimer': disclaimerHtml,
  '/' : indexHtml,
  '/index': indexHtml,
  '/pdf': pdfHtml,
  '/privacy': privacyHtml,
  '/terms': termsHtml,
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    let path = url.pathname;

    // remove .html extension
    if (path.endsWith('.html')) {
      path = path.slice(0, -5);
    }
    
    // handle root path
    if (path === '/') {
        path = '/index';
    }

    const html = pages[path];

    if (html) {
      return new Response(html, {
        headers: { 'Content-Type': 'text/html' },
      });
    }

    // Serve index.html for root, otherwise 404
    if (path === '/index') {
        return new Response(pages['/index'], {
            headers: { 'Content-Type': 'text/html' },
        });
    }

    return new Response('Not Found', { status: 404 });
  },
};