// This file is auto-generated by build.mjs. Do not edit manually.

import disclaimerHtml from './../dist/disclaimer.html';
import indexHtml from './../dist/index.html';
import pdfHtml from './../dist/pdf.html';
import privacyHtml from './../dist/privacy.html';
import termsHtml from './../dist/terms.html';

const pages = {
  '/disclaimer': disclaimerHtml,
  '/' : indexHtml,
  '/index': indexHtml,
  '/pdf': pdfHtml,
  '/privacy': privacyHtml,
  '/terms': termsHtml
};

export default {
  async fetch(request) {
    const url = new URL(request.url);
    let path = url.pathname;

    if (path.endsWith('.html')) {
      path = path.slice(0, -5);
    }
    if (path === '/') {
      path = '/index';
    }

    const html = pages[path];

    if (html) {
      return new Response(html, { headers: { 'Content-Type': 'text/html' } });
    }

    return new Response('Not Found', { status: 404 });
  },
};